name: NodeJS with Gulp

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /
#      - '**'          # Use this if you want to catch every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
